{% set name = "mistral-common" %}
{% set version = "1.5.1" %}
{% set python_min = python_min|default("3.8") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mistral_common-{{ version }}.tar.gz
  sha256: 6f2cc0209baeadc31f78c2275bddb734f167ad1734c8c8596f5338786c594537

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - poetry
  run:
    - python >={{ python_min }}
    - jsonschema
    - pillow <11.0.0,>=10.3.0
    - pydantic
    - requests
    - sentencepiece
    - tiktoken <0.8.0,>=0.7.0

test:
  imports:
    - mistral_common
  commands:
    - pip check
  requires:
    - numpy
    - pip
    - python {{ python_min }}
  downstreams:
    - mistral-inference

about:
  home: https://github.com/mistralai/mistral-common
  summary: Set of tools to help you work with Mistral models
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jeongseok-meta
